### ISSUE TITLE
Update minesweeper game and switch to new repo

### ISSUE THREAD

**Issue by io12** [nanochess/bootOS#14]
I'm the maintainer of the mine game linked in the README (https://gitlab.com/blevy/boot-sector-minesweeper). Thank you for including it! The version in the repo was just a prototype but the game is finished now. The gitlab repo is now a mirror of the official repo here: https://github.com/io12/BootMine. It would be awesome if you could update the README link and game files. Thanks.

**Comment by nanochess** [comment]
Just updated. Thanks for your message! Enjoy!
